"""Add type column

Revision ID: ff16ef8b8246
Revises: 
Create Date: 2024-12-20 23:13:28.486492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff16ef8b8246'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('name', sa.String(), nullable=True))
    op.add_column('avatar', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatar', 'type')
    op.drop_column('avatar', 'name')
    # ### end Alembic commands ###
