version: '3.9'
services:
  crud:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      crud-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ../downloads:/downloads
    networks:
      - crud-network
      - crud-db-network
      - rabbitmq-network
      - avatar-generator-network

  crud-db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 6
    networks:
      - crud-db-network

  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    networks:
      - rabbitmq-network

networks:
  crud-network:

  avatar-generator-network:
    external: true

  crud-db-network:

  rabbitmq-network:
